### ISSUE TITLE
PostgreSql exception on startup: connection already open

### ISSUE THREAD

**Issue by spoof3r** [bagetter/BaGetter#196]
### Describe the bug
When using the PostgreSql database type, an exception is thrown on startup that says `Connection already open`. The container then stops.

### To Reproduce
Run `docker compose up` on the following `docker-compose.yml` file:

``` yaml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  baget:
    image: bagetter/bagetter
    hostname: baget
    container_name: baget
    environment:
      - ApiKey=NUGET-SERVER-API-KEY
      - ASPNETCORE_URLS=http://+:5566
      - Storage__Type=FileSystem
      - Database__Type=PostgreSql
      - Database__ConnectionString=Host=postgres;Port=5432;Database=mydatabase;Username=postgres;Password=postgres;
      - Search__Type=Database
      - AllowPackageOverwrites=true
      - PackageDeletionBehavior=HardDelete
    ports:
      - "5566"
    networks:
      - mynetwork

volumes: 
  postgres_data:

networks:
  mynetwork:
    driver: bridge
```

### Expected behavior
BaGetter instance is started without a connection exception.

### Additional context
Here is output from Docker:

```
2024-11-22 13:43:01 Unhandled exception. System.InvalidOperationException: Connection already open
2024-11-22 13:43:01    at Npgsql.ThrowHelper.ThrowInvalidOperationException(String message)
2024-11-22 13:43:01    at Npgsql.NpgsqlConnection.CheckClosed()
2024-11-22 13:43:01    at Npgsql.NpgsqlConnection.Open(Boolean async, CancellationToken cancellationToken)
2024-11-22 13:43:01    at Npgsql.NpgsqlConnection.OpenAsync(CancellationToken cancellationToken)
2024-11-22 13:43:01    at BaGetter.Database.PostgreSql.PostgreSqlContext.RunMigrationsAsync(CancellationToken cancellationToken)
2024-11-22 13:43:01    at BaGetter.Web.IHostExtensions.RunMigrationsAsync(IHost host, CancellationToken cancellationToken)
2024-11-22 13:43:01    at BaGetter.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext()
2024-11-22 13:43:01 --- End of stack trace from previous location ---
2024-11-22 13:43:01    at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass8_0.<<OnExecuteAsync>b__0>d.MoveNext()
2024-11-22 13:43:01 --- End of stack trace from previous location ---
2024-11-22 13:43:01    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
2024-11-22 13:43:01    at BaGetter.Program.Main(String[] args)
2024-11-22 13:43:01    at BaGetter.Program.<Main>(String[] args)
```

**Comment by ahsanashraf** [comment]
Same logic works in .NET Core 3 baget v0.4.0-preview2.  Believe it may be related to EF8 + Npgsql updates since then.

**Comment by ahsanashraf** [comment]
I might suggest putting a TaskCompletionSource in IContext and SetResult() upon the completion of RunMigrationsAsync(). Then in PackageDatabase just await the Taskcompletionsource at the top of every method that might end up being called. I'm guessing index.razor ends up reaching FindAsync() during the migrations.

We kept our migrations in our service but also allowed it to be run via CLI so we could have an init job that would run migrations once in the case we wanted to deploy several pods at once. That way migrations wouldn't step on each other's toes.

**Comment by ds5678** [comment]
I'm encountering this too. I'll see if I can resolve it.
